// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCUyO7Tm13nLJpx9yQtAvVWMXwf80VlKs',
    appId: '1:328281519038:android:009376f1f1d63c8b367fef',
    messagingSenderId: '328281519038',
    projectId: 'ora-forma',
    storageBucket: 'ora-forma.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFSSCfvnKwFQoLrDOSY4PIQ4r3dB_8W4M',
    appId: '1:328281519038:ios:16d64e30053121b9367fef',
    messagingSenderId: '328281519038',
    projectId: 'ora-forma',
    storageBucket: 'ora-forma.firebasestorage.app',
    iosBundleId: 'com.example.catholicHabits',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7Dtew8HgzgBMYW8FRDi3VyDio26zKgh8',
    appId: '1:328281519038:web:faf921e5bc7253b2367fef',
    messagingSenderId: '328281519038',
    projectId: 'ora-forma',
    authDomain: 'ora-forma.firebaseapp.com',
    storageBucket: 'ora-forma.firebasestorage.app',
    measurementId: 'G-HMQPP5PCXT',
  );
}
